version: 1.0.0
includes:
  - types:
      filter: tag == "view_type"
routes:
  - get_projects_by_name:
  - project:
      eager_read_path:
        - tasks
      eager_update_path:
        - tasks
combined_routes:
  - project:
      combines:
        - task
