settings:
  application_tier: full-stack
  application_name: contacts-backend
  backend:
    languages:
      - typescript
    datasources:
      - sqlite
      - mysql
      - postgres
  datasource:
    pluralize_datatable_names: true
    use_stored_procedures: false
    use_optimistic_concurrency: false
    casing:
      file_names: auto
      types: auto
      fields: auto
      directories: auto
      objects: auto
      keywords: auto
  comments: simple
  other:
    organize_by_feature: false
    generate_file_hash_list: true
    error_on_hash_overwrite: true
    reverse_proxy: nginx
  languages:
    typescript:
      casing:
        file_names: kebab
        types: pascal
      library_reference_mode: bundled
      migrate_mode: bundled
      package_manager: auto
  frontend:
    framework: React
    generate_validators: true
